services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_USER: root
      DB_PASSWORD: example
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: mydatabase
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mydatabase
      MYSQL_ROOT_HOST: '%'
      MYSQL_DEFAULT_AUTHENTICATION_PLUGIN: caching_sha2_password
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -pexample"]
      interval: 10s
      timeout: 5s
      retries: 5
